version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5180:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - portfolio_network
    stdin_open: true
    tty: true

networks:
  portfolio_network:
